#!/usr/bin/env bash
# Writes lib/generated/neshan_secrets.g.dart from secrets.local.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/lib/generated/neshan_secrets.g.dart"
mkdir -p "$(dirname "$OUT")"

if [[ -f "$ROOT/secrets.local.sh" ]]; then
  # shellcheck source=/dev/null
  source "$ROOT/secrets.local.sh"
fi

API_KEY="${NESHAN_API_KEY:-}"
ANDROID_KEY="${NESHAN_ANDROID_KEY:-}"
MAP_KEY="${NESHAN_MAP_KEY:-}"

if [[ -z "$API_KEY" && -z "$ANDROID_KEY" && -z "$MAP_KEY" ]]; then
  cat >"$OUT" <<'EOF'
// GENERATED by scripts/sync_neshan_secrets.sh — do not edit or commit.
// Copy secrets.local.sh.example to secrets.local.sh and add your Neshan keys.
// ignore_for_file: constant_identifier_names

const String embeddedNeshanApiKey = '';
const String embeddedNeshanAndroidKey = '';
const String embeddedNeshanMapKey = '';
EOF
else
  cat >"$OUT" <<EOF
// GENERATED by scripts/sync_neshan_secrets.sh — do not edit or commit.
// ignore_for_file: constant_identifier_names

const String embeddedNeshanApiKey = '${API_KEY}';
const String embeddedNeshanAndroidKey = '${ANDROID_KEY}';
const String embeddedNeshanMapKey = '${MAP_KEY}';
EOF
fi

echo "Synced Neshan secrets -> lib/generated/neshan_secrets.g.dart"
